import { Property, BlogPost, NavItem } from './types';

export const NAV_ITEMS: NavItem[] = [
  { label: 'Inicio', path: '/' },
  { label: 'Propiedades', path: '/propiedades' },
  { label: 'Sobre Yoselin', path: '/sobre-yoselin' },
  { label: 'Comprar', path: '/comprar' },
  { label: 'Vender', path: '/vender' },
  { label: 'Blog', path: '/blog' },
  { label: 'Contacto', path: '/contacto' },
];

export const PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Penthouse de Lujo en Piantini',
    price: 850000,
    location: 'Piantini, Santo Domingo',
    type: 'Apartamento',
    beds: 4,
    baths: 4.5,
    sqft: 450,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    featured: true,
  },
  {
    id: '2',
    title: 'Villa Moderna con Vista al Mar',
    price: 1200000,
    location: 'Juan Dolio, San Pedro',
    type: 'Villa',
    beds: 5,
    baths: 6,
    sqft: 600,
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80',
    featured: true,
  },
  {
    id: '3',
    title: 'Apartamento Familiar en Naco',
    price: 325000,
    location: 'Naco, Santo Domingo',
    type: 'Apartamento',
    beds: 3,
    baths: 3.5,
    sqft: 220,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    featured: true,
  },
  {
    id: '4',
    title: 'Casa Contemporánea en Arroyo Hondo',
    price: 550000,
    location: 'Arroyo Hondo, Santo Domingo',
    type: 'Casa',
    beds: 4,
    baths: 4,
    sqft: 380,
    image: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: '5',
    title: 'Estudio Ejecutivo en Bella Vista',
    price: 185000,
    location: 'Bella Vista, Santo Domingo',
    type: 'Apartamento',
    beds: 1,
    baths: 1.5,
    sqft: 85,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: '6',
    title: 'Villa de Playa en Punta Cana',
    price: 2500000,
    location: 'Punta Cana, La Altagracia',
    type: 'Villa',
    beds: 6,
    baths: 7,
    sqft: 850,
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'Mejores zonas para vivir en Santo Domingo',
    excerpt: 'Descubre los sectores más exclusivos y con mejor calidad de vida en la capital dominicana.',
    date: '15 Mar 2024',
    image: 'https://images.unsplash.com/photo-1590059132213-f915347efb9b?auto=format&fit=crop&w=800&q=80',
    slug: 'mejores-zonas-santo-domingo',
  },
  {
    id: '2',
    title: 'Cómo comprar una propiedad en República Dominicana',
    excerpt: 'Guía paso a paso para inversionistas locales y extranjeros sobre el proceso legal y financiero.',
    date: '10 Mar 2024',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80',
    slug: 'guia-compra-rd',
  },
  {
    id: '3',
    title: 'Tendencias del mercado inmobiliario 2024',
    excerpt: 'Análisis de precios y nuevas oportunidades de inversión en el sector inmobiliario dominicano.',
    date: '05 Mar 2024',
    image: 'https://images.unsplash.com/photo-1460472178825-e5240623abe5?auto=format&fit=crop&w=800&q=80',
    slug: 'tendencias-mercado-2024',
  },
];
